# config/packages/easy_admin.yaml
easy_admin:
    design:
        templates:
            layout: 'admin/layout.html.twig'
    #design:
        #assets:
            #js:
                #- 'js/custom.js'